export const VerseCategories = [
  {
    id: 1,
    value: '',
    eng: 'All',
    geo: 'ყველა',
    rus: 'Все',
    color: 'green',
    icon: '',
  },
  {
    id: 2,
    value: 'MakeUp',
    eng: 'Make Up',
    geo: 'მაკიაჟი',
    rus: 'Макияж',
    color: '#de8787',
    icon: '',
  },
  {
    id: 3,
    value: 'Hairdressing Procedures',
    eng: 'Hairdressing Procedures',
    geo: 'თმის პროცედურები',
    rus: 'Парикмахерские услуги',
    color: '#de8787',
    icon: '',
  },

  {
    id: 4,
    value: 'Eyebrows and Eyelashes',
    eng: 'Eyebrows and Eyelashes',
    geo: 'წარბები და წამწამები',
    rus: 'Брови и ресницы',
    color: '#de8787',
    icon: '',
  },
  {
    id: 5,
    value: 'Nail Procedures',
    eng: 'Nail Procedures',
    geo: 'ფრჩხილები',
    rus: 'Ногтевой сервис',
    color: '#de8787',
    icon: '',
  },
  {
    id: 6,
    value: 'Permanent Makeup',
    eng: 'Permanent Makeup',
    geo: 'პერმანენტული მაკიაჟი',
    rus: 'Перманентный макияж',
    color: '#de8787',
    icon: '',
  },
  {
    id: 7,
    value: 'Cosmetology',
    eng: 'Cosmetology',
    geo: 'კოსმეტოლოგია',
    rus: 'Косметология',
    color: '#de8787',
    icon: '',
  },
  {
    id: 8,
    value: 'Epilation',
    eng: 'Epilation',
    geo: 'ეპილაცია',
    rus: 'Эпиляция',
    color: '#de8787',
    icon: '',
  },
  {
    id: 9,
    value: 'Spa',
    eng: 'Spa',
    geo: 'სპა',
    rus: 'Spa',
    color: '#de8787',
    icon: '',
  },
  {
    id: 10,
    value: 'Piercing',
    eng: 'Piercing',
    geo: 'პირსინგი',
    rus: 'Пирсинг',
    color: '#de8787',
    icon: '',
  },
  {
    id: 11,
    value: 'Tattoo',
    eng: 'Tattoo',
    geo: 'ტატუ',
    rus: 'Tattoo',
    onClick: 'tatto',
    color: '#de8787',
    icon: '',
  },
  {
    id: 12,
    value: 'Solarium',
    eng: 'Solarium',
    geo: 'სოლარიუმი',
    rus: 'Солярий',
    color: '#de8787',
    icon: '',
  },
  {
    id: 13,
    value: 'Beard Procedures',
    eng: 'Beard Procedures',
    geo: 'წვერის პროცედურები',
    rus: 'Уход за бородой',
    color: '#de8787',
    icon: '',
  },
];

export const ShopCategories = [
  {
    id: 1,
    title: 'All',
    geo: 'ყველა',
    onClick: ' ',
    color: '#333',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 2,
    title: 'Make Up',
    geo: 'მაკიაჟი',
    onClick: 'make',
    color: '#de8787',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 3,
    title: 'Brows',
    geo: 'წარბები',
    onClick: 'brow',
    color: 'brown',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 4,
    title: 'Eyelashes',
    geo: 'წამწამები',
    onClick: 'eyelash',
    color: '#de8787',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 5,
    title: 'Hairs',
    geo: 'თმა',
    onClick: 'hair',
    color: '#693434',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 6,
    title: 'Nails',
    geo: 'ფრჩხილები',
    onClick: 'nail',
    color: '#de8787',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 7,
    title: 'Cosmetology',
    geo: 'კოსმეტოლოგია',
    onClick: 'cosmetolo',
    color: '#de8787',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
  {
    id: 8,
    title: 'Stomatology',
    geo: 'სტომატოლოგია',
    onClick: 'stomato',
    color: '#46BCFF',
    icon: '',
    url: 'https://res.cloudinary.com/mimino/image/upload/v1663766973/ELAN/IMG_8122-min_ar7y5r.jpg',
  },
];
